# Generated by Django 2.0.1 on 2018-02-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceDB',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('symbol', models.CharField(max_length=5)),
                ('rank', models.IntegerField()),
                ('price_usd', models.FloatField()),
                ('price_btc', models.FloatField()),
                ('volume_24h', models.FloatField()),
                ('market_cap', models.FloatField()),
                ('available_supply', models.FloatField()),
                ('total_supply', models.FloatField()),
                ('max_supply', models.FloatField()),
                ('percent_change_1h', models.FloatField()),
                ('percent_change_24h', models.FloatField()),
                ('percent_change_7h', models.FloatField()),
                ('last_update', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
