# Generated by Django 2.0.1 on 2018-02-27 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CheckPrice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricedb',
            old_name='id',
            new_name='coinid',
        ),
    ]
