# Generated by Django 2.0.1 on 2018-02-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CheckPrice', '0002_auto_20180227_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricedb',
            name='last_update',
            field=models.CharField(max_length=25),
        ),
    ]
