# Generated by Django 2.0.1 on 2018-02-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CheckPrice', '0003_auto_20180227_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricedb',
            name='max_supply',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
